### ISSUE TITLE
Atom.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by leofle** [forabi/coffee-compiler#2]
atom.workspaceView is no longer available.
In most cases you will not need the view. See the Workspace docs for
alternatives: https://atom.io/docs/api/latest/Workspace.
If you do need the view, please use `atom.views.getView(atom.workspace)`,
which returns an HTMLElement.
```
Atom.Object.defineProperty.get (/Applications/Atom.app/Contents/Resources/app/src/atom.js:53:11)
Object.activate (/Users/studio4/.atom/packages/coffee-compiler/lib/coffee-compiler.coffee:7:13)
```

**Comment by forabi** [comment]
Please see the updated REAMDE file. The package is no longer maintained.
